---
hide_body: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: Seitentitel
- name: menu
  label: Menu
  type: field_group
  fields:
  - name: left
    label: Left
    type: field_group
    fields:
    - name: weight
      label: Weight
      type: text
      hidden: false
      default: ''
    hidden: false
    default: ''
  - name: foot
    label: Foot
    type: field_group
    fields:
    - name: weight
      label: Weight
      type: text
      hidden: false
      default: ''
    hidden: false
    default: ''
  hidden: true
  default: 
